-define(ALLOWED_CHARS, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890").
-define(NOTHING, "").
-define(NOT_IMPLEMENTED, throw(not_implemented)).
-define(WORKER(Module, Args), {Module, {Module, start_link, Args}, permanent, 2000, worker, [Module]}).
-define(WORKER(Module), ?WORKER(Module, [])).
-define(SUPERVISOR(Module, Args), {Module, {Module, start_link, Args}, permanent, infinity, supervisor, [Module]}).
-define(SUPERVISOR(Module), ?SUPERVISOR(Module, [])).
-define(NAMESPACE(Name), list_to_atom("jmeta_" ++ atom_to_list(Name))).
